-- ============================================================
-- 045 — Operations priority queue
--
-- Persistent queue of operational action items for coordinators
-- and managers. Items can be auto-generated by the system
-- (compliance sweeps, incident creation) or created manually.
-- Each item has priority, ownership, escalation tracking, and
-- resolution history.
-- ============================================================

CREATE TABLE operations_queue (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  -- Priority and type
  priority        TEXT        NOT NULL DEFAULT 'warning'
    CHECK (priority IN ('critical', 'urgent', 'warning', 'informational')),
  category        TEXT        NOT NULL DEFAULT 'other'
    CHECK (category IN (
      'safeguarding', 'compliance', 'staffing', 'onboarding',
      'incident', 'medication', 'shift_coverage', 'other'
    )),

  -- Content
  title           TEXT        NOT NULL,
  description     TEXT,

  -- Linked entity
  entity_type     TEXT,
  entity_id       UUID,
  entity_url      TEXT,

  -- Ownership
  assigned_to     TEXT,
  assigned_at     TIMESTAMPTZ,
  due_date        TIMESTAMPTZ,

  -- Status
  status          TEXT        NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'resolved', 'dismissed')),

  -- Source
  auto_generated  BOOLEAN     DEFAULT FALSE,
  source          TEXT,

  -- Escalation tracking
  escalation_triggered_at      TIMESTAMPTZ,
  escalation_acknowledged_at   TIMESTAMPTZ,
  escalation_acknowledged_by   TEXT,

  -- Resolution
  resolution_notes  TEXT,
  resolved_at       TIMESTAMPTZ,
  resolved_by       TEXT,

  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ops_queue_company_status   ON operations_queue(company_id, status);
CREATE INDEX idx_ops_queue_priority         ON operations_queue(company_id, priority) WHERE status = 'open';
CREATE INDEX idx_ops_queue_due              ON operations_queue(due_date) WHERE status IN ('open', 'in_progress');
CREATE INDEX idx_ops_queue_entity           ON operations_queue(entity_type, entity_id) WHERE entity_id IS NOT NULL;
