-- ============================================================
-- 055 — Operational Intelligence Orchestration Priorities
--
-- Persists ownership state, acknowledgements, snooze windows,
-- suppression rules, and audit logs for unified priority items.
-- Generated priority content is computed at runtime by the
-- orchestration engine; only user-driven state is stored here.
-- ============================================================

-- ── Priority state table ──────────────────────────────────────────────────────
-- Stores per-priority lifecycle state (assign, snooze, acknowledge, resolve)

CREATE TABLE IF NOT EXISTS orchestration_priority_states (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  -- Priority identifier (generated by orchestration engine, not a FK)
  priority_id     TEXT        NOT NULL,

  -- Status lifecycle
  status          TEXT        NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'acknowledged', 'in_progress', 'snoozed', 'resolved', 'escalated', 'dismissed')),

  -- Ownership
  owner_name      TEXT,
  owner_id        UUID        REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Snooze
  snoozed_until   TIMESTAMPTZ,
  snoozed_by      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  snooze_reason   TEXT,

  -- Acknowledgement
  acknowledged_by UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  acknowledged_at TIMESTAMPTZ,

  -- Resolution
  resolved_by     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved_at     TIMESTAMPTZ,
  resolution_note TEXT,

  -- Dismiss
  dismissed_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  dismissed_at    TIMESTAMPTZ,
  dismiss_reason  TEXT,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (company_id, priority_id)
);

CREATE INDEX idx_orch_states_company    ON orchestration_priority_states(company_id);
CREATE INDEX idx_orch_states_status     ON orchestration_priority_states(company_id, status);
CREATE INDEX idx_orch_states_priority   ON orchestration_priority_states(priority_id);

-- ── Suppression windows ───────────────────────────────────────────────────────
-- Admin-defined windows that suppress specific category/source alerts temporarily

CREATE TABLE IF NOT EXISTS orchestration_suppressions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id  UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  category    TEXT,       -- PriorityCategory — NULL = all categories
  source_id   TEXT,       -- source system entity ID — NULL = any
  reason      TEXT        NOT NULL,
  suppress_until TIMESTAMPTZ NOT NULL,

  created_by  UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orch_suppressions_company ON orchestration_suppressions(company_id);
CREATE INDEX idx_orch_suppressions_until   ON orchestration_suppressions(suppress_until);

-- ── Audit log ────────────────────────────────────────────────────────────────
-- Immutable record of every state change on every priority item

CREATE TABLE IF NOT EXISTS orchestration_audit_log (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id   UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  priority_id  TEXT        NOT NULL,

  action       TEXT        NOT NULL
    CHECK (action IN (
      'priority_generated',
      'priority_grouped',
      'acknowledged',
      'assigned',
      'snoozed',
      'resolved',
      'escalated',
      'dismissed'
    )),

  actor_id     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_name   TEXT,
  note         TEXT,
  metadata     JSONB,

  occurred_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orch_audit_company   ON orchestration_audit_log(company_id, occurred_at DESC);
CREATE INDEX idx_orch_audit_priority  ON orchestration_audit_log(priority_id);
CREATE INDEX idx_orch_audit_action    ON orchestration_audit_log(action);

-- ── RLS ──────────────────────────────────────────────────────────────────────

ALTER TABLE orchestration_priority_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE orchestration_suppressions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE orchestration_audit_log       ENABLE ROW LEVEL SECURITY;

-- Admins access their own company's data only
CREATE POLICY "orch_states_company_isolation" ON orchestration_priority_states
  USING (
    company_id = (
      SELECT company_id FROM admin_users WHERE user_id = auth.uid() LIMIT 1
    )
  );

CREATE POLICY "orch_suppressions_company_isolation" ON orchestration_suppressions
  USING (
    company_id = (
      SELECT company_id FROM admin_users WHERE user_id = auth.uid() LIMIT 1
    )
  );

CREATE POLICY "orch_audit_company_isolation" ON orchestration_audit_log
  USING (
    company_id = (
      SELECT company_id FROM admin_users WHERE user_id = auth.uid() LIMIT 1
    )
  );

-- Service role bypasses RLS for system writes
CREATE POLICY "orch_states_service_role"       ON orchestration_priority_states  USING (auth.role() = 'service_role');
CREATE POLICY "orch_suppressions_service_role"  ON orchestration_suppressions     USING (auth.role() = 'service_role');
CREATE POLICY "orch_audit_service_role"         ON orchestration_audit_log        USING (auth.role() = 'service_role');

-- ── Updated-at trigger ────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_orchestration_states_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_orch_states_updated_at
  BEFORE UPDATE ON orchestration_priority_states
  FOR EACH ROW EXECUTE FUNCTION update_orchestration_states_updated_at();
